# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    versio

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [10]:
a.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
#python -c "import numpy as np; print(np.add.__doc__)"
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via t

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [20]:
b = np.zeros(10)
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [23]:
c = np.arange(10, 50, 1)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
c[::-1] #or np.flip()

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
search = np.array([1,2,0,0,4,0])
np.where(search > 0)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [30]:
#d = np.zeros(9)
#d[0] = 1 
#d[4] = 1 
#d[8] = 1
#d.reshape(3,3)

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [37]:
#np.random.rand(27).reshape(3,3,3)
np.random.rand(3, 3, 3)

array([[[0.08683452, 0.21919219, 0.33026043],
        [0.11287246, 0.10816274, 0.65471102],
        [0.74006002, 0.20272029, 0.57836092]],

       [[0.15886609, 0.20222574, 0.52512284],
        [0.47469985, 0.42824491, 0.4358815 ],
        [0.89946404, 0.48786367, 0.96130781]],

       [[0.05821005, 0.49519689, 0.87636693],
        [0.31504678, 0.13481427, 0.82681056],
        [0.61730838, 0.41366231, 0.27348574]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [38]:
r = np.random.rand(10, 10)
print(np.max(r))
print(np.min(r))

0.9929529121570243
0.0007808685318192454


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [40]:
np.mean(np.random.rand(30))

0.5884551150313838

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [44]:
#a = np.ones(9)
#a[4] = 0
#a.reshape(3, 3)

a = np.ones((3, 3))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [58]:
a = np.ones((5,5))
a[:, [0,-1]] = 0
a[[0,-1], :] = 0
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan
# false
# false
# nan
# true
# false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [70]:
#g = np.zeros((5,5))
#count =1
#for i in range(4):
#    g[i+1, i] = count
#    count += 1

#g

np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [81]:
a = np.zeros((8,8))
a[0::2, 1::2] = 1
a[1::2, 0::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [87]:
a = np.random.rand(6,7,8)
np.unravel_index(100, a.shape)

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [96]:
#a = np.zeros(8)
#b = np.zeros(8)
#a[1::2] = 1
#b[0::2] = 1
#np.tile([a,b], (4, 1))

np.tile([[0,1],[1,0]], (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [101]:
#L2 norm
#a = np.random.rand(5,5)
#b = np.linalg.norm(a, axis=1, keepdims=True)

#a / b

a = np.random.rand(5,5)
b = (a-np.mean(a)) / np.std(a)
b

array([[-0.27869463, -1.03024718, -0.42256552, -0.22943741, -0.16856866],
       [ 1.08434727, -1.69983689,  0.14017867,  1.54821284,  0.03842149],
       [-0.1889874 ,  1.61323609,  0.08448384, -2.31057106,  1.0706403 ],
       [ 0.01432571,  1.82158642, -0.70434663, -0.20354685, -0.20532842],
       [ 1.00364213, -0.63576827, -1.38712031,  0.84459708,  0.20134739]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
colluh = np.dtype([
    ('R', np.ubyte),
    ('G', np.ubyte),
    ('B', np.ubyte),
    ('A', np.ubyte)
])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.random.rand(5,3)
b = np.random.rand(3, 2)
np.matmul(a,b) #or a @ b

array([[0.98284458, 0.68017911],
       [0.70982127, 0.26227232],
       [0.56131888, 0.08654679],
       [1.32152917, 0.8019207 ],
       [0.82527337, 0.3116193 ]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [116]:
#a = np.arange(100)
#a = np.where(((a <=8) & (a >=3)), -a, a)
#a
a = np.arange(100)
a[(a >= 3) & (a <= 8)] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
#first, sum range(5) = 10, start at -1, so then =9 (-1 + 0 + 1 ... =9)
#second replace python with numpy sum, second positional arg is axis, so its =10 (axis 0 and -1 are the same, numpy sums across the axis doesnt subtract -1)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#elementwise exponents, legal
# bit shifts are legal
# comparison between Z and -Z, legal
# imaginary * Z, legal
# legal, just changes to float dtype
# truth value error, illegal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
#nan
# warning, 0
#warning, -9.22337204e+18

#### 29. How to round away from zero a float array ? (★☆☆)

In [124]:
a = np.random.rand(100) * 200 - 100 #.astype(float) if needed, rand is already float
np.copysign(np.ceil(np.abs(a)), a)

array([ 40., -28.,   6., -61.,  69.,  -6., -21.,  69., -57., -46., -35.,
       -86., -98.,  19.,  62., -18.,  -8.,  26., -74., -50., -22.,  36.,
        -7.,  22.,  37.,  42.,  18., -70., -74.,  51.,   7., -81.,  81.,
        94.,  37.,  51.,  -9.,  53., -25.,  16., -79., -42., -87.,  67.,
        33., -73.,  79., -70., -77.,  78.,  64.,  92.,  50.,  54., -70.,
        89.,   1.,  50., -33.,  66.,  30.,  50., 100.,  49.,  23.,  80.,
       -31., -22., -69., -56.,  70.,  94.,  34., -69., -66.,  42., -45.,
       -86., -51.,  69., -35.,  57.,  51., -65., -45., -14., -55.,  48.,
       -14., -34.,   4., -15., -95.,  31.,  51.,  78.,  71., -98., -71.,
        39.])

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.random.rand(100) * 200 - 100 
a = np.copysign(np.ceil(np.abs(a)), a)

b = np.random.rand(100) * 200 - 100 
b = np.copysign(np.ceil(np.abs(b)), b)

np.intersect1d(a,b)

array([-97., -96., -91., -86., -82., -75., -71., -70., -55., -50., -45.,
       -44., -36., -31., -25., -22., -20., -17., -14., -10.,   5.,   7.,
        14.,  25.,  34.,  39.,  40.,  52.,  55.,  70.,  75.,  77.,  85.,
        92.])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all='ignore') 

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#no, emath will return a complex value, standard sqrt will be within real number space (putting aside that np.sqrt(-1) returns nan, which when == with anything is false regardless)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [129]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - 1
tomorrow = np.datetime64('today', 'D') + 1

print(today)
print(yesterday)
print(tomorrow)

2026-08-08
2026-08-07
2026-08-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [130]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [134]:
a = np.random.rand(100)
b = np.random.rand(100)
b += a
a /= -2
b*=a

b

array([-2.30967087e-01, -2.98514441e-01, -7.49175742e-01, -1.78211586e-02,
       -5.69030805e-02, -6.78770302e-01, -3.16830960e-02, -3.82921355e-01,
       -4.02357122e-01, -7.04064634e-03, -6.47271141e-01, -7.03946139e-02,
       -9.21291120e-02, -7.59863621e-01, -3.59930896e-01, -1.64449998e-01,
       -6.32611184e-02, -1.85199734e-01, -9.18705314e-03, -2.44704783e-01,
       -8.80249439e-01, -2.25110802e-01, -1.30465506e-01, -1.60248837e-01,
       -7.30217229e-01, -5.77286624e-01, -6.29020283e-01, -1.21497157e-01,
       -3.03928103e-02, -1.13199697e-01, -3.12644073e-01, -5.59995088e-01,
       -7.16077715e-04, -2.50279088e-01, -1.99731728e-02, -1.72559716e-02,
       -1.46461124e-01, -9.01021563e-01, -9.99099254e-02, -5.28237509e-02,
       -4.49719332e-01, -1.64932392e-01, -1.23621147e-01, -1.23720602e-01,
       -2.21349407e-02, -3.34045451e-02, -7.41974793e-01, -7.45391062e-01,
       -1.14587833e-02, -7.52864201e-01, -2.53163450e-01, -6.58274580e-02,
       -1.14054637e-01, -

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
a = np.random.rand(100) * 100
b = a.astype(int)
c = np.floor(a) 
d =  a - np.mod(a, 1)
e = np.trunc(a)

e

array([42., 92., 57., 31., 38., 53., 31., 46., 26., 43., 97.,  7., 79.,
       84.,  2., 91.,  7.,  4., 37., 72., 14., 67., 78., 56., 22., 88.,
       98., 95., 55., 24., 65., 27., 90., 91., 28., 19., 54., 13., 79.,
       15., 82., 25., 43., 13., 52., 33., 54., 38., 23., 99., 68., 71.,
       90., 49., 63., 79., 60., 69., 50., 20., 79., 40., 11., 16.,  1.,
       41., 23., 25., 85., 54., 86., 27., 15., 34., 95., 69., 27.,  8.,
       42., 59., 70., 94., 99.,  0., 38., 46., 26., 55., 27., 80., 98.,
       63., 39., 39., 53., 60., 21., 52., 94., 57.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [146]:
np.tile(np.arange(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [148]:
np.fromiter((i for i in range(10)), dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [151]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [155]:
a = np.random.rand(10)
np.sort(a)

array([0.12706324, 0.14744417, 0.22231779, 0.33190497, 0.48768535,
       0.50518869, 0.51416902, 0.57903471, 0.76962633, 0.94664366])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [156]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [158]:
a = np.random.rand(10)
b = np.random.rand(10)

np.array_equal(a, b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [160]:
a = np.arange(10)
a.setflags(write=False)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [167]:
a = np.random.rand(10, 2)
r = np.hypot(a[:, 0], a[:, 1])
t = np.arctan2(a[:, 1], a[:, 0])

np.column_stack((r,t))

array([[0.8419795 , 0.57982535],
       [0.59416956, 1.25464022],
       [0.64828399, 1.02986472],
       [0.8451303 , 1.44573044],
       [0.81499506, 0.50148494],
       [0.46861892, 0.33262877],
       [0.44708863, 0.66904438],
       [0.44045211, 0.08042726],
       [0.78872953, 0.5254815 ],
       [0.93937914, 0.09758013]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [175]:
a = np.random.rand(10)
a[np.argmax(a)] = 0
a

array([0.68770028, 0.23389301, 0.4167758 , 0.81385329, 0.00430776,
       0.85731593, 0.68344219, 0.45587522, 0.02986579, 0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [187]:
dtype = np.dtype([
    ('x', float),
    ('y', float),
    ])

a = np.linspace(0, 1, 5, dtype=float)
b = np.linspace(0, 1, 5, dtype=float)

X, Y = np.meshgrid(a,b)


c = np.zeros((5,5), dtype=dtype)

c['x'] = X
c['y'] = Y

c

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [190]:
x = np.random.rand(5).reshape(5,1)
y = np.random.rand(3).reshape(1,3)

cauchy = 1/(x-y)

cauchy

array([[ 1.05022357,  2.01033615,  1.16757929],
       [ 1.92237711, 15.28109623,  2.35580157],
       [ 1.01836639,  1.8967562 ,  1.12833767],
       [ 4.19677286, -4.619564  ,  7.01395112],
       [ 3.94153416, -4.9741184 ,  6.32899428]])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [195]:
iinfo = [np.int8, np.int16, np.int32, np.int64,
                 np.uint8, np.uint16, np.uint32, np.uint64]

for dtype in iinfo:
    info = np.iinfo(dtype)
    print(dtype, info.min, info.max)


finfo = [np.float16, np.float32, np.float64]

for dtype in finfo:
    info = np.finfo(dtype)
    print(dtype, info.min, info.max)

<class 'numpy.int8'> -128 127
<class 'numpy.int16'> -32768 32767
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.uint8'> 0 255
<class 'numpy.uint16'> 0 65535
<class 'numpy.uint32'> 0 4294967295
<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.float16'> -65500.0 65500.0
<class 'numpy.float32'> -3.4028235e+38 3.4028235e+38
<class 'numpy.float64'> -1.7976931348623157e+308 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.inf)
# then just print whatever size array

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [196]:
a = np.random.rand(100) * 200 - 100
b = 5
a[np.argmin(abs(a-b))]

5.3289830968519425

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [198]:
dtype = np.dtype([
    ('position', 'float', (2,)),
    ('color', np.uint8, (3,)),
])

a = np.zeros(5, dtype=dtype)
a

array([([0., 0.], [0, 0, 0]), ([0., 0.], [0, 0, 0]),
       ([0., 0.], [0, 0, 0]), ([0., 0.], [0, 0, 0]),
       ([0., 0.], [0, 0, 0])],
      dtype=[('position', '<f8', (2,)), ('color', 'u1', (3,))])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [201]:
a = np.random.rand(100, 2)
b = a[:, None, :]
c = a[None, :, :]

e = c-b 

f = np.sqrt(e[:, :, 0]**2 + e[:, :, 1]**2)

f

array([[0.        , 0.77663317, 0.57764147, ..., 0.81627766, 0.86196254,
        0.74215511],
       [0.77663317, 0.        , 0.20599589, ..., 0.43931007, 0.4421659 ,
        0.10918975],
       [0.57764147, 0.20599589, 0.        , ..., 0.49136755, 0.5138081 ,
        0.21681442],
       ...,
       [0.81627766, 0.43931007, 0.49136755, ..., 0.        , 0.04866169,
        0.33292792],
       [0.86196254, 0.4421659 , 0.5138081 , ..., 0.04866169, 0.        ,
        0.3397134 ],
       [0.74215511, 0.10918975, 0.21681442, ..., 0.33292792, 0.3397134 ,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [204]:
a = np.random.rand(5).astype(np.float32)

b = a.view(np.int32)
b[:] = a


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
np.genfromtext('.csv', delimiter=',')

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
np.ndenumerate()

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [211]:
a = np.linspace(-1, 1, 5).reshape(5,1)
b = np.linspace(-1, 1, 5).reshape(1,5)

c = a**2 + b**2

np.exp(-c)

array([[0.13533528, 0.2865048 , 0.36787944, 0.2865048 , 0.13533528],
       [0.2865048 , 0.60653066, 0.77880078, 0.60653066, 0.2865048 ],
       [0.36787944, 0.77880078, 1.        , 0.77880078, 0.36787944],
       [0.2865048 , 0.60653066, 0.77880078, 0.60653066, 0.2865048 ],
       [0.13533528, 0.2865048 , 0.36787944, 0.2865048 , 0.13533528]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [223]:
p = 3

a = np.random.rand(5,5) * 100
a.ravel()[np.random.default_rng().choice(a.size, size=p, replace=False)] = 0
a

array([[75.68212066, 15.51704634,  0.        , 19.46281348, 91.53269385],
       [20.85962839, 41.88457154, 91.00316803,  0.        , 54.01304559],
       [55.46654365, 44.11921347, 63.26322626, 30.4875373 , 92.81797484],
       [93.1590483 , 48.57264593, 69.21316462,  0.        , 77.29087467],
       [27.81482637,  7.04543163, 94.33075162, 33.44516621, 51.69199278]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [229]:
a = np.random.rand(5,5) * 100

a - np.mean(a, axis = 1, keepdims=True)

array([[  1.73383759,   2.26224222,  -0.09046379, -21.31701995,
         17.41140393],
       [ 10.3122452 , -15.13708228,  36.31510302, -11.04446096,
        -20.44580498],
       [ 22.43621895,  14.61048052, -19.80700342, -14.84676119,
         -2.39293486],
       [  7.93256394, -10.92261436, -29.61988461,  30.80942968,
          1.80050535],
       [ -6.21783893,  -1.57827825,  14.26580089,   8.70241773,
        -15.17210144]])

#### 59. How to sort an array by the nth column? (★★☆)

In [231]:
n = 2

a = np.random.rand(5,5) * 100

a[a[:, n].argsort()]

array([[92.5422855 , 57.70110011, 17.68173304, 66.4889742 , 46.93424085],
       [59.89091632, 88.38387831, 25.38500756, 19.20456886, 51.36894725],
       [38.43998988, 26.26904076, 25.64384761, 13.34929496, 39.83335434],
       [35.24733676, 46.96556521, 32.11418426, 30.14237812, 38.61493522],
       [98.32431765, 42.45161551, 66.98346441, 39.13053704, 21.8249397 ]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
a = np.full((5,5), np.nan)
a[:, 1:] = 1
np.isnan(a).all(axis=0) #.any() for a single output

array([ True, False, False, False, False])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [239]:
g = 5 

a = np.random.rand(5,5) * 100

a.ravel()[np.argmin(abs(a - g))]

2.7381349868338622

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [253]:
a = np.random.rand(1,3)
b = np.random.rand(3,1)

iter = np.nditer([a,b,None])

for x, y, z in iter:
    z[...] = x + y

c = iter.operands[2]

c

array([[1.04000116, 1.38453583, 1.32333303],
       [0.54438134, 0.88891601, 0.82771321],
       [0.79443004, 1.13896472, 1.07776191]])

#### 63. Create an array class that has a name attribute (★★☆)

In [254]:
class special(np.ndarray):
    def __new__(cls, input, name="default"):
        obj = np.asarray(input).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, "name", "default")

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [258]:
a = np.random.rand(100) * 100
b = np.random.randint(0, a.size, size=50)
#for y in b:
#    a[y] += 1

np.add.at(a,b,1)


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [259]:
x = np.random.rand(10) * 100
f = np.random.rand(10,10) * 100
i = np.random.randint(0, f.size, x.size)

np.add.at(f.ravel(),i,x)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [267]:
len(np.unique(np.random.randint(0, 256, size=(5, 5, 3), dtype=np.uint8).reshape(-1, 3), axis=0))

25

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [270]:
a = np.ones((2,2,2,2))

np.sum(a, axis=(-2,-1))

array([[4., 4.],
       [4., 4.]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [275]:
n = 3 #subset count

d = np.random.rand(10)
s = np.random.randint(0, n, d.size)

np.bincount(s, weights=d) / np.bincount(s)

array([0.18732025, 0.42058297, 0.63260362])

#### 69. How to get the diagonal of a dot product? (★★★)

In [277]:
# really poor wording tbh, a dot prod is between two vectors which will result in another single scalar, you cannot have a diag on this... 
# Honestly throughout the mathematical defs of things haven't been followed with the questions. It should say the matrix product between arrays.

a = np.random.rand(3,2)
b = np.random.rand(2,3)

np.einsum("ij,ji->i", a, b)

array([0.94156511, 0.40086975, 0.80449739])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [280]:
a = np.array([1,2,3,4,5])

b = np.zeros(a.size + (a.size - 1) *3)

b[::4] = a

b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [282]:
a = np.random.rand(5,5,3)
b = np.random.rand(5,5)

a * b[:,:, None]


array([[[4.93148792e-01, 3.25510290e-01, 8.17451583e-01],
        [7.51199785e-01, 8.48768943e-01, 5.44358891e-01],
        [4.62334006e-02, 3.45019248e-01, 3.26621750e-01],
        [9.29651255e-02, 2.77404226e-02, 3.64449604e-02],
        [6.23432950e-01, 4.90488918e-01, 2.11139365e-02]],

       [[2.31292411e-01, 1.54690972e-01, 1.93577361e-01],
        [2.20964865e-01, 1.27915417e-01, 2.13197782e-01],
        [2.92136130e-01, 2.74736768e-01, 2.00629784e-01],
        [1.81843796e-02, 1.93046213e-02, 1.10426810e-02],
        [3.11019462e-01, 1.14516095e-01, 1.22298507e-01]],

       [[4.77250962e-01, 1.77620663e-01, 2.75880983e-01],
        [5.83267371e-01, 3.30799696e-01, 2.73703125e-01],
        [3.32087971e-01, 1.96960680e-02, 6.55619650e-01],
        [6.25959250e-01, 2.44150656e-01, 2.60264229e-01],
        [2.41844503e-01, 7.16078371e-02, 3.13741699e-02]],

       [[1.07977566e-01, 6.59706980e-01, 7.21918319e-01],
        [1.40897017e-02, 7.81701813e-03, 4.31195505e-03],
        

#### 72. How to swap two rows of an array? (★★★)

In [283]:
a = np.random.rand(5,5)

a[[4,1]] = a[[1,4]]

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [291]:
a = np.random.randint(0, 10, size=(10,3))

p = np.vstack([
    a[:, [0,1]],
    a[:, [1,2]],
    a[:, [2,0]],
])

b = np.sort(p, axis=1)

np.unique(b, axis=0)

array([[0, 1],
       [0, 2],
       [0, 4],
       [0, 6],
       [0, 7],
       [1, 5],
       [1, 7],
       [2, 3],
       [2, 5],
       [2, 6],
       [3, 5],
       [3, 6],
       [3, 8],
       [4, 4],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 6],
       [5, 7],
       [5, 8],
       [7, 7],
       [8, 9]])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
start = 1
end = 4
c = np.arange(start, end)

a = np.repeat(np.arange(c.size), c)

(np.bincount(a) == c).all()

array([ True,  True,  True])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [301]:
a = np.random.rand(3,3,3)

w = (2,2,2)

b = np.lib.stride_tricks.sliding_window_view(a, w)

c = np.mean(b, axis=(-3,-2,-1))

c

array([[[0.63127946, 0.45775607],
        [0.64840389, 0.54232806]],

       [[0.55574728, 0.52067526],
        [0.56030267, 0.54095214]]])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [306]:
n = 5

z = np.arange(n)

w = 3

b = np.lib.stride_tricks.sliding_window_view(z, w)

b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [313]:
a = np.random.randint(0,2,10).astype(bool)
np.logical_not(a, out=a)
print(a)

b = np.random.rand(10) * 200 - 100
np.negative(b, out=b)
print(b)


[ True  True False  True  True  True  True False  True False]
[-27.6305807   72.24280444 -67.85536203  -9.95091143 -46.55164511
  16.47601466  70.16026825  54.08520573  92.59657653  -4.87358018]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
n = 3 #line count

p  = np.array([-1, 1])
p0 = np.random.randint(0, 10, size=(n,2))
p1 = np.random.randint(0, 10, size=(n,2))

v = p1 - p0
w = p - p0

np.abs(v[:, 0] * w[:, 1] - v[:, 1] * w[:, 0]) / np.sqrt(v[:, 0]**2 + v[:, 1]**2)

array([8.47998304, 2.68328157, 1.58113883])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [318]:
n = 3 #line count
n1 = 2 #point count

p  = np.random.randint(0, 10, size=(n1,2))
p0 = np.random.randint(0, 10, size=(n,2))
p1 = np.random.randint(0, 10, size=(n,2))

v = p1 - p0
w = p[:, None, :] - p0[None, :, :]

np.abs(v[None, :, 0] * w[:, :, 1] - v[None, :, 1] * w[:, :, 0]) / np.sqrt(v[:, 0]**2 + v[:, 1]**2)

array([[3.72620657, 2.94484824, 1.34164079],
       [0.58834841, 1.02429504, 1.78885438]])

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [323]:
a = np.random.rand(5,5,5)

def e(a, c, s, f=0):
    c = np.array(c)
    s = np.array(s)

    out = np.full(s, f, dtype=a.dtype)

    half = s // 2
    start = c - half
    end = start + s

    s_start = np.maximum(start, 0)
    s_end = np.minimum(end, np.array(a.shape))

    d_start = s_start - start
    d_end = d_start + (s_end - s_start)

    s_slices = tuple(slice(s, e) for s, e in zip(s_start, s_end))
    d_slices = tuple(slice(s, e) for s, e in zip(d_start, d_end))

    out[d_slices] = a[s_slices]

    return out

e(a, c = (0,0,0), s = (3,3,3), f=-1)

array([[[-1.        , -1.        , -1.        ],
        [-1.        , -1.        , -1.        ],
        [-1.        , -1.        , -1.        ]],

       [[-1.        , -1.        , -1.        ],
        [-1.        ,  0.94233707,  0.62776545],
        [-1.        ,  0.83271877,  0.20567805]],

       [[-1.        , -1.        , -1.        ],
        [-1.        ,  0.34137201,  0.87069851],
        [-1.        ,  0.12608769,  0.88625143]]])

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [321]:
z = np.arange(1, 15)
r = np.lib.stride_tricks.sliding_window_view(z, 4)

r


array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [324]:
a = np.random.rand(5, 5)
np.linalg.matrix_rank(a)

5

#### 83. How to find the most frequent value in an array?

In [328]:
a = np.random.randint(0 , 3, size=(5,5))
b, c = np.unique(a, return_counts=True)
b[np.argmax(c)]

2

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [329]:
a = np.random.rand(10,10)

np.lib.stride_tricks.sliding_window_view(a, (3,3))

array([[[[0.45868127, 0.07466645, 0.45547293],
         [0.45783263, 0.48519157, 0.99317883],
         [0.60424796, 0.78071945, 0.30380082]],

        [[0.07466645, 0.45547293, 0.39174282],
         [0.48519157, 0.99317883, 0.93995178],
         [0.78071945, 0.30380082, 0.71152998]],

        [[0.45547293, 0.39174282, 0.03752932],
         [0.99317883, 0.93995178, 0.67259342],
         [0.30380082, 0.71152998, 0.00178838]],

        [[0.39174282, 0.03752932, 0.36715237],
         [0.93995178, 0.67259342, 0.85565382],
         [0.71152998, 0.00178838, 0.30626053]],

        [[0.03752932, 0.36715237, 0.2569653 ],
         [0.67259342, 0.85565382, 0.00875494],
         [0.00178838, 0.30626053, 0.51080988]],

        [[0.36715237, 0.2569653 , 0.13742974],
         [0.85565382, 0.00875494, 0.91446326],
         [0.30626053, 0.51080988, 0.36504935]],

        [[0.2569653 , 0.13742974, 0.85658941],
         [0.00875494, 0.91446326, 0.41179564],
         [0.51080988, 0.36504935, 0.71293715]],


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [331]:
class special(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index

        np.ndarray.__setitem__(self, (i,j), value)
        np.ndarray.__setitem__(self, (j,i), value)

a = np.zeros((5,5)).view(special)

a[0,1] = 2
print(a)

[[0. 2. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [332]:
n = 5 #shape
p = 3 #count 

a = np.random.rand(p,n,n)
b = np.random.rand(p,n,1)

(a @ b).sum(axis=0)


array([[2.66254973],
       [2.73630091],
       [1.615915  ],
       [3.37694214],
       [3.64141852]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [333]:
a = np.random.rand(16,16)
a.reshape(4,4,4,4).sum(axis=(1,3))

array([[ 6.95122295,  9.43936206,  7.51698304,  9.07353196],
       [ 9.15305378,  9.04573591,  8.01796333,  6.38362903],
       [ 8.15623215,  6.75201943,  7.19606658,  9.76476331],
       [ 7.46206888, 11.72440437,  8.97612838,  9.02838905]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [335]:
a = np.random.randint(0,2, size=(10,10))

n = (
    a[:-2, :-2] + a[:-2, 1:-1] + a[:-2, 2:] + a[1:-1, :-2] + a[1:-1, 2:] + a[2:, :-2] + a[2:, 1:-1] + a[2:, 2:]
)

c = a[1:-1, 1:-1]

c[...] = ((c==1) & ((n==2) | (n==3))) | ((c==0) * (n==3))

c

array([[0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]])

#### 89. How to get the n largest values of an array (★★★)

In [336]:
n = 5 #count

a = np.random.rand(100)

a[np.argpartition(a, -n)[-n:]]

array([0.94194978, 0.95366487, 0.95932061, 0.96354336, 0.97492702])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [337]:
n = 3 #number vectors
s = 5 #vector size

v = [np.random.randint(0,10, size=s) for _ in range(n)]

np.stack(np.meshgrid(*v, indexing="ij"), axis=-1).reshape(-1,n)

array([[7, 3, 1],
       [7, 3, 6],
       [7, 3, 1],
       [7, 3, 2],
       [7, 3, 5],
       [7, 9, 1],
       [7, 9, 6],
       [7, 9, 1],
       [7, 9, 2],
       [7, 9, 5],
       [7, 5, 1],
       [7, 5, 6],
       [7, 5, 1],
       [7, 5, 2],
       [7, 5, 5],
       [7, 7, 1],
       [7, 7, 6],
       [7, 7, 1],
       [7, 7, 2],
       [7, 7, 5],
       [7, 9, 1],
       [7, 9, 6],
       [7, 9, 1],
       [7, 9, 2],
       [7, 9, 5],
       [4, 3, 1],
       [4, 3, 6],
       [4, 3, 1],
       [4, 3, 2],
       [4, 3, 5],
       [4, 9, 1],
       [4, 9, 6],
       [4, 9, 1],
       [4, 9, 2],
       [4, 9, 5],
       [4, 5, 1],
       [4, 5, 6],
       [4, 5, 1],
       [4, 5, 2],
       [4, 5, 5],
       [4, 7, 1],
       [4, 7, 6],
       [4, 7, 1],
       [4, 7, 2],
       [4, 7, 5],
       [4, 9, 1],
       [4, 9, 6],
       [4, 9, 1],
       [4, 9, 2],
       [4, 9, 5],
       [1, 3, 1],
       [1, 3, 6],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 5],
       [1,

#### 91. How to create a record array from a regular array? (★★★)

In [338]:
a = np.random.randint(0,5, size=(2,2))

np.core.records.fromarrays(a.T, names = 'id,value', formats='i4,i4')

rec.array([(2, 3), (1, 2)],
          dtype=[('id', '<i4'), ('value', '<i4')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [339]:
a = np.random.rand(100)

print(a**3)
print(np.power(a,3))
print(a*a*a)

[1.13672067e-01 2.50817582e-03 4.23445809e-01 7.62783668e-01
 2.00911717e-01 2.25782532e-01 5.99660266e-01 6.53871570e-02
 1.30774304e-02 7.23544108e-02 3.55784504e-01 2.13701467e-01
 9.50104107e-01 5.09067241e-02 3.46696928e-01 2.38079708e-03
 5.37116458e-02 2.36127985e-02 3.00671448e-01 6.34398413e-01
 2.74496830e-03 3.74510593e-01 3.11676165e-01 8.59496764e-01
 3.05270461e-01 1.04959539e-01 4.31535186e-01 6.80966095e-02
 2.03494578e-01 3.99618311e-01 4.32256728e-01 1.29199332e-02
 2.69490914e-01 1.66048574e-04 6.29870130e-01 1.26237131e-04
 1.29541675e-02 2.27402569e-02 5.16807655e-01 8.17164915e-01
 5.78090197e-01 3.57270901e-03 2.67395284e-01 8.17330037e-02
 2.65240520e-03 1.68436554e-03 1.42500930e-01 3.26405732e-02
 2.71990464e-01 1.71078358e-02 2.01036877e-02 1.55782996e-04
 6.64678533e-03 2.86227926e-01 2.67710343e-01 1.42011986e-02
 2.10996041e-01 5.52820980e-02 6.44799299e-03 1.78616666e-01
 1.41298944e-01 1.39386531e-02 6.64938992e-02 5.08442583e-01
 1.10728143e-02 3.155916

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [341]:
a = np.random.randint(0,3, size=(8,3))
b = np.random.randint(0,3, size=(2,2))

for r in b:
    m = np.isin(a,r).sum(axis=1) == len(r)
    print(a[m])

[[1 1 2]
 [2 1 1]
 [0 2 0]]
[[1 0 0]
 [0 1 0]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [342]:
a = np.random.randint(0,4, size=(10,3))

a[np.any(a != a[:, [0]], axis=1)]

array([[2, 0, 0],
       [2, 3, 3],
       [0, 2, 1],
       [1, 0, 0],
       [2, 3, 1],
       [0, 2, 2],
       [2, 3, 1],
       [2, 3, 2],
       [3, 1, 1]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [345]:
a = np.arange(50)

((a[:, None] >> np.arange(8)[::-1]) & 1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 1],
       [0,

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [347]:
a = np.random.randint(0,3, size=(2,2))
np.unique(a, axis=0)

array([[1, 2],
       [2, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [348]:
a = np.random.rand(3)
b = np.random.rand(3)

print(np.einsum('i,i->', a,b))

print(np.einsum('i,j->ij', a, b))

print(np.einsum('i->', a))

print(np.einsum('i,i->i', a, b))

1.0079286343130542
[[0.24848138 0.28851311 0.23752956]
 [0.44974998 0.52220719 0.42992722]
 [0.24817854 0.28816148 0.23724006]]
1.6285044306982903
[0.24848138 0.52220719 0.23724006]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [352]:
x = np.random.randint(0,6, size =1)
y = np.random.randint(0,6, size = 1)

d = np.sqrt(np.diff(x)**2 + np.diff(y)**2)

s = np.concatenate(([0], np.cumsum(d)))

s_n = np.linspace(0, s[-1], 20)

x_n = np.interp(s_n, s, x)
y_n = np.interp(s_n, s, y)

print(x_n)
print(y_n)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [355]:
n = 5

x = np.random.randint(0,6, size=(10,3)).astype(float)

x[0] = [1,2,2]
x[1] = [3,0,2]

x[2,0] += 0.2
x[4,1] += 0.3

m = (
    (x==np.floor(x)).all(axis =1) & (x >=0).all(axis=1) & (x.sum(axis=1) == n)
)

x[m]

array([[1., 2., 2.],
       [3., 0., 2.]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [356]:
x = np.random.randn(100)
n = 10000

s = np.random.choice(x, size=(n, x.size), replace=True)

m = s.mean(axis=1)

np.percentile(m, [2.5, 97.5])


array([-0.0289017 ,  0.34744378])